pyproject.toml

All the submodules in `optimas` where missing when installing with `pip` because they where not included in `[tool.setuptools.packages.find]`. This PR fixes that.

Fix missing modules in `pyproject.toml`

---

examples/ionization_injection/template_simulation_script.py
examples/ionization_injection_mf/template_simulation_script.py

Removes the `use_all_mpi_ranks=False` option from the FBPIC example scripts. This was causing the simulations to fail when trying to run with several GPUs.

Fix FBPIC examples

---

.readthedocs.yaml

The docs build will now fail if any warning is raised. This prevents any issues (e.g., with formatting) that would otherwise not be noticed.

Fail docs on warning

---

pyproject.toml

It seems that the tests are currently failing due to the new release of libEnsemble. This PR pins the libEnsemble version on the `main` branch to `0.9.3` until we are ready to upgrade to `0.10`.

Pin libensemble version

---

.github/workflows/publish-to-pypi.yml

Adds a workflow that will take care of automatically uploading `optimas` to PyPI every time we make a new release.

Publish to PyPI on release

---

optimas/explorations/base.py

A bug in the order with which the `Exploration` is initialized was preventing the `executable` provided to the `TemplateEvaluator` from being added to the `sim_files` list.
Fixes #97

Fix bug with executable in `sim_files`

---

README.md
doc/source/user_guide/installation_local.rst
doc/source/user_guide/installation_maxwell.rst
doc/source/user_guide/installation_perlmutter.rst

- Updates installation instructions to use the PyPI releases instead of the Github repo. (@ax3l, @RemiLehe, I removed the `pip install torch` line from the Perlmutter instructions because this dependency is already installed when doing `pip install optimas`. This works well on my side, at least on Maxwell).
- Add PyPI, Zenodo, license and tests badges.

Change instructions to install from PyPI and add post-release badges

---

doc/source/api/generators.rst
optimas/generators/__init__.py
optimas/generators/ax/service/ax_client.py
tests/test_ax_generators.py

This PR adds a new generator that allows the user to provide a custom `AxClient`. This allows for maximum tunability and control of the optimization.
Note: If the ``AxClient`` contains ``outcome_constraints``, these will appear in the ``optimas`` log as optimization objectives. They are still being correctly used as constraints by the ``AxClient``, and the optimization will work as expected. This is only an issue on ``optimas``, which fails to properly recognize them because optimization constraints have not yet been implemented.

Implement generator with user-defined `AxClient`

---

optimas/explorations/base.py
optimas/gen_functions.py
optimas/generators/ax/developer/multitask.py
optimas/generators/ax/service/base.py
optimas/generators/base.py
optimas/utils/other.py
tests/test_ax_generators.py

The `Generator` stores a list of all the generated trials, as well as the underlying surrogate model (if any). However, this information was so far only available within the `gen_function` of `libEnsemble` and was not being given back to `optimas`. This is because the generator given to `libE` in the `gen_specs` is passed to the generator worker as a copy (because this worker is in a different process), and therefore the original one created by the user was not being updated (see related issue https://github.com/Libensemble/libensemble/issues/975). This is a problem, because in principle we could allow the user to inspect the generator after a run is completed to look at the surrogate model, trials, etc.
This PR implements a solution that consists on returning the copy of the generator …

Update generator after running exploration

---

doc/source/user_guide/installation_perlmutter.rst

Having an example submission script is useful to the user.
Note that these instructions will technically only work once #88 is merged.

Documentation: add submission script on Perlmutter

---

doc/source/user_guide/installation_juwels.rst
doc/source/user_guide/installation_maxwell.rst

Adds instructions for installing `optimas` on the JUWELS Booster, including how to get FBPIC and Wake-T in the same enviroment.
It also includes an example submission script.
When testing `optimas` on JUWELS, I noticed that things like the GPU assignment are not working as expected. This is partly on our side (we need to merge #88 first) and also what I think might be a bug in their system (I contacted support and will update this once I get a reply).
Update: It is a bug on JUWELS and they are working on it. Basically, when running with several workers and several GPUs per worker, the first worker gets only only GPU assigned (all ranks use GPU 0).

Add installation instructions for JUWELS Booster

---

optimas/generators/ax/developer/multitask.py

The latest Ax release changes the name of `get_MTGP` to `get_MTGP_LEGACY`.
(see https://github.com/facebook/Ax/pull/1688)

Fix issue with latest Ax release

---

.github/workflows/unix.yml

This PR makes sure that the tests pass in all currently supported python versions (3.8 - 3.11). Also, since some dependencies like Ax seem to sometimes have breaking changes, the tests will now run daily to make sure we catch any issues with new releases of dependencies.

Run tests daily and with all supported python versions

---

optimas/explorations/base.py
optimas/gen_functions.py
optimas/generators/ax/developer/multitask.py
optimas/generators/base.py
pyproject.toml
tests/test_exploration_resume.py

This PR enables two new workflows addressing  #107:
1. Running an exploration in substeps:
```python
exploration = Exploration(
generator=gen,
evaluator=ev,
max_evals=30,
sim_workers=2
)
exploration.run(n_evals=3)
exploration.run(n_evals=4)
exploration.run(n_evals=10)
exploration.run(n_evals=5)
exploration.run()  # Run remaining evaluations.
```
This can be useful when running `optimas` interactively. It would allow the user, for example, to tune the hyperparameters of the generator between each `run`.
2. Resuming from a previous exploration that was executed in the same `exploration_dir_path`.
```python
exploration = Exploration(
generator=gen,
evaluator=ev,
max_evals=40,
sim_workers=2,
resume=True
)
exploration.run()
```
This allows us to seamlessly continue a previous exploration
This …

Allow resuming an exploration and running in substeps

---

optimas/evaluators/multitask_evaluator.py

Fixes a tiny typo in the docs.

Fix typo in `MultitaskEvaluator` docstring

---

doc/source/conf.py

The latest version of the theme raises a warning if `navigation_with_keys` is not explicitly set, which causes readthedocs to report a failed build. This PR simply sets it to the new default.

Avoid pydata theme warning

---

optimas/explorations/base.py
tests/test_exploration_resume.py

Changes the default value of some `Exploration` parameters:
- `run_async=False`. I think this is a more adequate default. Only when the time cost can change significantly between evaluations should the user set `run_async=True`. Otherwise, the current default was resulting in some performance loss, because new evaluations are no longer generated in batch unless the previous evaluations finished at exactly the same time.
- `max_evals=np.inf`. By default, allow the exploration to run indefinitely. This is useful when running interactively in substeps with `Exploration.run(n_evals)` without predefining a maximum limit.
- `sim_workers=1`. By default, run with only 1 worker.

Change `Exploration` defaults

---

optimas/generators/ax/base.py

Fixes a bug where the Ax logs were still being displayed even if `verbose_logging=False` was given to the `AxClient`. This was only happening when using `spawn` multiprocessing (the default on Windows and Mac).
The logs are mostly a duplicate of the optimas logs, so disabling them keeps the output cleaner.

Disable Ax logs

---

README.md
doc/source/user_guide/basic_usage/running_with_simulations.rst

Document features introduced in recent PRs:
- Custom environments (#108).
- `ChainEvaluator` (#110).
Also includes general improvements to the README.

Document new features and improve README

---

optimas/explorations/base.py
pyproject.toml
tests/test_exploration_resume.py

Use the new `libE_specs` options `"save_H_on_completion"`, `"save_H_with_date"` and `"H_file_prefix"` to customize the name of the history file and make sure that there is only one file per exploration.

Use new libE save history options

---

optimas/generators/ax/service/ax_client.py
optimas/generators/ax/service/base.py
optimas/generators/ax/service/multi_fidelity.py
optimas/generators/ax/service/single_fidelity.py
tests/test_ax_generators.py

Currently, it is not possible to skip the initialization step of the Ax generators. This is not convenient, because it means that the first trials suggested by the generator will always be quasi-random, even if the user supplied external data to initialize the model. This PR fixes this issue by reducing the number of Sobol trials if external data is provided by the user.
There were several options to implement this:
1. **Allow the user to set `n_init=0`**: In this case, we would simply not add a Sobol step to the AxClient. However, this is not safe in all cases, because the BO step requires some initial data to be able to start. Also, it you want to resume a previous exploration, you would need to change the input script to set `n_init=0` to avoid rerunning the Sobol step.
2. **Do not add …

Reduce number of initialization evaluations if external data is supplied

---

.github/workflows/publish-to-pypi.yml
.github/workflows/unix.yml
.readthedocs.yaml
optimas/core/parameter.py
optimas/generators/ax/base.py
optimas/generators/ax/service/base.py
optimas/generators/ax/service/custom_ax.py
optimas/generators/ax/service/multi_fidelity.py
optimas/generators/ax/service/single_fidelity.py
optimas/generators/base.py
pyproject.toml
tests/test_ax_generators.py

This PR adds support for interactive explorations where the range of varying parameters can be updated, or their values fixed. For example:
```python
var1 = VaryingParameter("x0", -50.0, 5.0)
var2 = VaryingParameter("x1", -5.0, 15.0)
obj = Objective("f", minimize=False)
generator = AxSingleFidelityGenerator(
varying_parameters=[var1, var2],
objectives=[obj],
fit_out_of_design=True,
)
evaluator = FunctionEvaluator(function=eval_func_sf)
exploration = Exploration(
generator=generator,
evaluator=evaluator,
sim_workers=2,
)
exploration.run(n_evals=5)
var1.update_range(-20., 0.)
generator.update_parameter(var1)
exploration.run(n_evals=10)
var1.fix_value(-9)
generator.update_parameter(var1)
exploration.run(n_evals=5)
var1.free_value()
generator.update_parameter(var1)
exploration.run(n_evals=5) …
```

Support changing the range and fixing the value of `VaryingParameter`s

---

optimas/evaluators/base.py
optimas/generators/ax/service/base.py
optimas/generators/base.py
tests/test_ax_generators.py

Fixes a bug introduced in #150, where the `dtype` of the `VaryingParameters` was not being used by the Ax Service generators. The type was therefore being inferred by Ax, which sometimes would set a float as an int.
It also fixes an issue where parameters with a dtype other than float would crash the exploration.
The tests have been updated to prevent a random crash in the new test introduced in #150.

Fix bug with parameter type in Ax generators

---

optimas/explorations/base.py

Updates the name of the threading communications from `local_threading` to `threads`, as now defined in libEnsemble https://github.com/Libensemble/libensemble/pull/1188. This change preserves backward compatibility with `local_threading`.

Rename `local_threading` to `threads`

---

optimas/utils/logger.py

Log optimas output to `stdout` instead of `stderr`. This makes it cleaner (it won't be mixed with warnings and logs from other dependencies) and is more in line with the user expectations.

Log to `stdout`

---

doc/source/user_guide/installation_maxwell.rst

Fixes a typo in the name of the cupy package.

Fix typo in Maxwell installation instructions

---

doc/source/user_guide/installation_maxwell.rst

Make sure python 3.11 is used on Maxwell, since 3.12 is not yet supported and 3.9 seems to be having issues.

Use Python 3.11 on Maxwell

---

optimas/diagnostics/exploration_diagnostics.py
tests/resources/template_simulation_script_moo.py
tests/test_exploration_diagnostics.py

Adds new methods to the `ExplorationDiagnostics` to:
- plot the Pareto frontier
- get the best evaluations
- get the paths to the evaluation folders
- delete the evaluation folders

Add new plots and methods to `ExplorationDiagnostics`

---

optimas/sim_functions.py

Fixes a bug where the trailing newline of the template script would be removed when generating the simulation scripts. This was leading to issues with ASTRA simulations.

Keep trailing newline in template script

---

optimas/diagnostics/exploration_diagnostics.py
optimas/explorations/base.py
optimas/utils/other.py
tests/test_exploration_diagnostics.py

This adds the method `plot_history` to the `ExplorationDiagnostics` class.
This is the first of a series of PRs to import existing post processing tools to the new Optimas version.

Adds a new plot to `ExplorationDiagnostics`

---

optimas/diagnostics/exploration_diagnostics.py
optimas/utils/other.py
tests/test_exploration_diagnostics.py

Example:
```py
gs = mpl.gridspec.GridSpec(2, 2, wspace=0.2, hspace=0.3)
diags.plot_history(top=10, show_legend=True, subplot_spec=gs[:, 0])
diags.plot_pareto_front(show_best_evaluation_indices=True, show_legend=True, subplot_spec=gs[0, 1])
diags.plot_worker_timeline(subplot_spec=gs[1, 1])
```

Allow plots in `ExplorationDiagnostics` to be drawn in a grid

---

optimas/diagnostics/exploration_diagnostics.py

It allows the top evaluation indices to be shown in `plot_history`.
Example:
```py
gs = mpl.gridspec.GridSpec(2, 2, wspace=0.2, hspace=0.3)
diags.plot_history(top=10, show_top_evaluation_indices=True, show_legend=True, subplot_spec=gs[:, 0])
diags.plot_pareto_front(show_best_evaluation_indices=True, show_legend=True, subplot_spec=gs[0, 1])
diags.plot_worker_timeline(subplot_spec=gs[1, 1])
```
In addition, helper functions to access the parameter's objects by their name have been added to `ExplorationDiagnostics`.

Show evaluation indices of "top" simulations

---

optimas/diagnostics/exploration_diagnostics.py
tests/test_exploration_diagnostics.py

- `print_best_evaluations` shows a table with the top scoring evaluations in the given objective.
example:
```py
diags.print_best_evaluations(top=5)
```
```
Top 5 evaluations in metric f1 (minimize = False):  [168, 125, 74, 47, 84]
f1          f2         x0         x1
168  897.356441  432.315095 -41.014755  12.668375
125  806.129161  709.940631 -46.410127  11.699764
74   770.447289  616.824412 -47.631321  11.454126
47   757.891119  726.930477 -49.191153  12.272802
84   739.310092  378.713516 -35.158977  12.262404
```
- `print_evaluation` shows the relevant parameters of a given evaluation.
example:
```py
diags.print_evaluation(168)
```
```
Evaluation 168: 
sim_id = 168
dir_path = tests_output/test_exploration_diagnostics/evaluations/sim0168
objective functions:
f1 =  897.35644
f2 = …
```

Add methods to print information about the evaluations

---

optimas/evaluators/template_evaluator.py
optimas/sim_functions.py

This PR allows the user to set the names of the standard output and error files. This name was previously hard-coded to `out.txt` and `err.txt`, which caused them to be overwritten when running several simulations with a `ChainEvaluator`.

Expose `stdout` and `stderr` filenames to user

---

optimas/core/trial.py
optimas/generators/ax/service/ax_client.py
optimas/generators/ax/service/base.py
optimas/generators/ax/service/multi_fidelity.py
optimas/generators/ax/service/single_fidelity.py
tests/test_ax_generators.py

Adds the possibility of providing `parameter_constraints` and `outcome_constraints` in the generators that use the Ax Service API.
Example:
```python
var1 = VaryingParameter("x0", -50.0, 5.0)
var2 = VaryingParameter("x1", -5.0, 15.0)
obj = Objective("f", minimize=False)
p1 = Parameter("p1")
gen = AxSingleFidelityGenerator(
varying_parameters=[var1, var2],
objectives=[obj],
analyzed_parameters=[p1],
parameter_constraints=["x0 + x1 <= 10"],
outcome_constraints=["p1 <= 30"]
)
```

Add support for constraints in Ax generators using the Service API

---

optimas/evaluators/template_evaluator.py
optimas/sim_functions.py
pyproject.toml
tests/resources/template_simulation_script.py
tests/test_template_evaluator.py

This PR adds a new `timeout` option to the `TemplateEvaluator` that will kill an evaluation if its runtime reaches this value. It also adds better handling of evaluations that failed to be launched, which are now properly labeled as failed by using the new `polling_loop` from https://github.com/Libensemble/libensemble/pull/1229.

Add evaluation timeout and improve handling of evaluations that failed to launch

---

README.md
doc/source/user_guide/dependencies.rst
doc/source/user_guide/installation_juwels.rst
doc/source/user_guide/installation_local.rst
doc/source/user_guide/installation_maxwell.rst
doc/source/user_guide/installation_perlmutter.rst

- Adds the `conda-forge` badge to the readme.
- Updates installation instructions to include the `conda-forge` option.
- `pip install optimas[all]` -> `pip install 'optimas[all]'`. This should work in all terminals.

Add conda-forge badge and update docs

---

pyproject.toml

Update requirements to latest libEnsemble release in preparation for `v0.4`.

Require `libEnsemble >= 1.2`

---

.github/workflows/unix-openmpi.yml
.github/workflows/unix.yml

- Separate MPICH and openMPI tests to reduce test runtime.
- Update deprecated actions.
- Run tests only on pull request, and no longer on push.

Update and speedup tests

---

optimas/diagnostics/exploration_diagnostics.py
optimas/evaluators/function_evaluator.py
tests/test_function_evaluator.py

Adds a new `create_evaluation_dirs` option to `FunctionEvaluator` so that a sim dir will be created for each evaluation (just like with a `TemplateEvaluator`.

Allow `FunctionEvaluator` to create evaluation dirs

---

optimas/diagnostics/ax_model_manager.py
optimas/diagnostics/exploration_diagnostics.py
optimas/explorations/base.py
optimas/gen_functions.py
optimas/generators/ax/developer/multitask.py
optimas/generators/ax/service/base.py
optimas/generators/base.py
optimas/utils/other.py
pyproject.toml
tests/resources/template_simulation_script.py
tests/test_ax_generators.py
tests/test_gpu_resources.py

This PR uses the new `"gen_on_manager"` option from libEnsemble, allowing the generator to run in the same process as the manager. This avoids passing the generator to the worker as a copy, so that the generator that `gen_f` uses is the same instance that was created by the user. This simplifies the code (no need to update the gen in a dirty way after the exploration run) and avoids potentially unexpected behavior that could result from operating on copies of the generator.
Additionally, a new test has been added to check that GPU resource allocation works properly.

Run generator on manager

---

doc/environment.yaml
optimas/generators/ax/developer/multitask.py
optimas/generators/ax/import_error_dummy_generator.py
optimas/generators/ax/service/base.py
pyproject.toml
tests/test_ax_generators.py

Fixes a bug where an AxClient could not be loaded from a json file because the SOBOL step had `num_trials = 0`. The fix is trivial (single line) if we require Ax >= 0.3.5.

Fix bug when loading AxClient from json and require `Ax >= 0.3.5`

---

optimas/sim_functions.py

This just prevents assigning `np.nan` to data fields in libE_output which are not `float`, but does nothing when the data is not `float`.
Possibly, we would want to assign default values to other parameter types such as `int`.
It addresses this issue https://github.com/optimas-org/optimas/issues/218

Assign `np.nan` only when the type is `float`

---

doc/environment.yaml
pyproject.toml

Using `ax-platform 0.4.0` instead of `ax-platform 0.4.1` avoids the error `cannot import name 'register_metric' from 'ax.storage.metric_registry'`

Fix ax-platform version

---

examples/multi_stage/template_simulation_script

The lower boundary for particles and fields in the RZ mode of WarpX have to be set to `none`. This commit updates the input file accordingly.

Update boundary conditions in WarpX example

---

examples/multi_stage/analysis_script.py

In the issue reported in https://github.com/optimas-org/optimas/issues/236, it turns out that, for some input parameters, the simulation returned on only 2 macroparticles at the end of the acceleration stage. 
In this case, this case, the emittance should be exactly 0, but due to floating-point errors, the quantity `x2*u2 -xu**2` happened to be negative.
This PR checks that the number of particles is bigger than 2, to avoid this type of error

Use more robust calculation of the emittance.

---

doc/source/user_guide/installation_maxwell.rst

After the latest maxwell upgrade the intel.2020 module is no longer available.
This is an update of the documentation on how to install optimas on maxwell.

fix maxwell documentation

---

.github/workflows/unix-noax.yml
optimas/utils/ax/ax_model_manager.py

One way to prevent failure when ax not present.
Ref:
https://peps.python.org/pep-0563
https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING

Use postponed annotations (PEP 563)

---

optimas/explorations/base.py
tests/test_exploration_run_exception.py

Make sure `Exploration.run` can handle an exception and that the cwd is restored even when an exception occurs.
This prevents an issue when running in Jupyter notebooks, where if the cell execution is cancelled (of the cell that calls Exploration.run) the cwd not be restored and would require restarting the whole notebook.

Handle exception during exploration run

---

optimas/evaluators/function_evaluator.py
optimas/sim_functions.py
tests/test_function_evaluator.py

Currently, when using a `FunctionEvaluator`, the output of the exploration and of every runner gets printed in the same terminal. This results in very messy output.
This PR adds the option of redirectling the logs of the `FunctionEvaluator` to a dedicated file for each worker, similarly to how it works with the `TemplateEvaluator`.
When enabling the new `redirect_logs_to_file` option, the `FunctionEvaluator` will force the use of `sim_dirs_make` so that every worker prints to a log file in a separate `sim` directory.

Allow `FunctionEvaluator` to redirect `stdout` and `stderr` to a log file
